=== ProfDrRausch/Pro12/restaurant/data/vorrat.dtd
<!ELEMENT vorrat (produkt+)>

<!ELEMENT produkt (name, anzahl, preis)>
<!ATTLIST produkt kategorie (Basisgericht | Beilage | Getraenk) #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT anzahl (#PCDATA)>
<!ELEMENT preis (#PCDATA)>

=== ProfDrRausch/Pro12/restaurant/data/2025.07.01-17-00-25_vorrat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vorrat SYSTEM "vorrat.dtd">
<vorrat>
    <produkt kategorie="Basisgericht">
        <name>Garnelen</name>
        <anzahl>4</anzahl>
        <preis>13.50</preis>
    </produkt>
    <produkt kategorie="Basisgericht">
        <name>Hueftsteak</name>
        <anzahl>4</anzahl>
        <preis>13.00</preis>
    </produkt>
    <produkt kategorie="Basisgericht">
        <name>Tofu</name>
        <anzahl>4</anzahl>
        <preis>8.50</preis>
    </produkt>
    <produkt kategorie="Basisgericht">
        <name>Wienerschnitzel</name>
        <anzahl>5</anzahl>
        <preis>10.50</preis>
    </produkt>
    <produkt kategorie="Beilage">
        <name>Bratkartoffeln</name>
        <anzahl>5</anzahl>
        <preis>1.50</preis>
    </produkt>
    <produkt kategorie="Beilage">
        <name>Nudeln</name>
        <anzahl>5</anzahl>
        <preis>4.50</preis>
    </produkt>
    <produkt kategorie="Beilage">
        <name>Pommes</name>
        <anzahl>4</anzahl>
        <preis>2.50</preis>
    </produkt>
    <produkt kategorie="Beilage">
        <name>Salat</name>
        <anzahl>5</anzahl>
        <preis>2.25</preis>
    </produkt>
    <produkt kategorie="Beilage">
        <name>Suppe</name>
        <anzahl>4</anzahl>
        <preis>1.50</preis>
    </produkt>
    <produkt kategorie="Getraenk">
        <name>Bier</name>
        <anzahl>4</anzahl>
        <preis>3.00</preis>
    </produkt>
    <produkt kategorie="Getraenk">
        <name>Wasser</name>
        <anzahl>4</anzahl>
        <preis>1.50</preis>
    </produkt>
    <produkt kategorie="Getraenk">
        <name>Wein</name>
        <anzahl>5</anzahl>
        <preis>4.00</preis>
    </produkt>
</vorrat>
